version: '3.8'

services:
  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    container_name: elearning_client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - elearning_network

  server:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    container_name: elearning_server
    ports:
      - "8000:8000"
    volumes:
      - ./src/server/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://user:password@db:3306/elearning
      - JWT_SECRET=your_jwt_secret_here
      - YOUTUBE_API_KEY=your_youtube_api_key_here
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - elearning_network

  db:
    image: mysql:8.0
    container_name: elearning_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: elearning
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - elearning_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  elearning_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local