services:
  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    container_name: elearning_client
    ports:
      - "3000:3000"
    volumes:
      - ./src/client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  server:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    container_name: elearning_server
    ports:
      - "8000:8000"
    volumes:
      - ./src/server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://user:password@db:3306/elearning
    depends_on:
      - db
    restart: unless-stopped

  admin:
    build:
      context: ./src/admin
      dockerfile: Dockerfile
    container_name: elearning_admin
    ports:
      - "5000:5000"
    volumes:
      - ./src/admin:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: elearning_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: elearning
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: