services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elearning_server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://user:password@db:3306/elearning
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: elearning_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: elearning
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: