// <auto-generated />
using System;
using Infrastructure.data.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250419230322_UpdateV10")]
    partial class UpdateV10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entites.Class", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedBy")
                        .HasColumnType("text");

                    b.Property<string>("facultyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("lecturerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("majorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("facultyId");

                    b.HasIndex("lecturerId")
                        .IsUnique();

                    b.HasIndex("majorId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Domain.Entites.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("audioUrl")
                        .HasColumnType("text");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedBy")
                        .HasColumnType("text");

                    b.Property<string>("imageUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("lessonId")
                        .HasColumnType("text");

                    b.Property<int>("likeCount")
                        .HasColumnType("integer");

                    b.Property<string>("postId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updatedBy")
                        .HasColumnType("text");

                    b.Property<string>("videoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("createdBy");

                    b.HasIndex("lessonId");

                    b.HasIndex("postId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Domain.Entites.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedBy")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("documentUrl")
                        .HasColumnType("text");

                    b.Property<string>("facultyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("majorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("thumbNail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("createdBy");

                    b.HasIndex("facultyId");

                    b.HasIndex("majorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Domain.Entites.Exam", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClassId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedBy")
                        .HasColumnType("text");

                    b.Property<int>("duration")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("endTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("startTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("subjectId")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("totalQuestion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId");

                    b.HasIndex("createdBy");

                    b.HasIndex("subjectId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Domain.Entites.ExamQuestion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("examId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("questionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("examId");

                    b.HasIndex("questionId");

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("Domain.Entites.ExamResultByUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedBy")
                        .HasColumnType("text");

                    b.Property<double>("duration")
                        .HasColumnType("double precision");

                    b.Property<string>("examId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("score")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("createdBy");

                    b.HasIndex("examId");

                    b.ToTable("ExamResultsByUser");
                });

            modelBuilder.Entity("Domain.Entites.ExamSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("classId")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedBy")
                        .HasColumnType("text");

                    b.Property<string>("examDay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("examId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("subjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("superVisoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("classId");

                    b.HasIndex("createdBy");

                    b.HasIndex("examId");

                    b.HasIndex("subjectId");

                    b.HasIndex("superVisoryId");

                    b.ToTable("ExamSchedules");
                });

            modelBuilder.Entity("Domain.Entites.Faculty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedBy")
                        .HasColumnType("text");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("createdBy");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("Domain.Entites.Lecturer", b =>
                {
                    b.Property<string>("cardId")
                        .HasColumnType("text");

                    b.Property<string>("facultyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("joinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("majorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("cardId");

                    b.HasIndex("facultyId");

                    b.HasIndex("majorId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Lecturers", (string)null);
                });

            modelBuilder.Entity("Domain.Entites.Lesson", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text");

                    b.Property<string>("courseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("documentUrl")
                        .HasColumnType("text");

                    b.Property<int>("position")
                        .HasColumnType("integer");

                    b.Property<string>("thumbnail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("urlVideo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("courseId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Domain.Entites.Major", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedBy")
                        .HasColumnType("text");

                    b.Property<string>("facultyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("createdBy");

                    b.HasIndex("facultyId");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("Domain.Entites.Notify", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("LecturercardId")
                        .HasColumnType("text");

                    b.Property<string>("StudentcardId")
                        .HasColumnType("text");

                    b.Property<string>("classId")
                        .HasColumnType("text");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedBy")
                        .HasColumnType("text");

                    b.Property<string>("facultyId")
                        .HasColumnType("text");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("isForAll")
                        .HasColumnType("boolean");

                    b.Property<bool>("isRead")
                        .HasColumnType("boolean");

                    b.Property<string>("majorId")
                        .HasColumnType("text");

                    b.Property<string>("receiverId")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LecturercardId");

                    b.HasIndex("StudentcardId");

                    b.HasIndex("classId");

                    b.HasIndex("createdBy");

                    b.HasIndex("facultyId");

                    b.HasIndex("majorId");

                    b.HasIndex("receiverId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Domain.Entites.Permisstion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("assignedUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedBy")
                        .HasColumnType("text");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("isManagedCourses")
                        .HasColumnType("boolean");

                    b.Property<bool>("isManagedSubjects")
                        .HasColumnType("boolean");

                    b.Property<bool>("isManagedUsers")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("assignedUserId");

                    b.HasIndex("createdBy");

                    b.ToTable("Permisstions");
                });

            modelBuilder.Entity("Domain.Entites.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("answers")
                        .HasColumnType("text");

                    b.Property<string>("audioUrl")
                        .HasColumnType("text");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("correctAnswer")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedBy")
                        .HasColumnType("text");

                    b.Property<string>("facultyId")
                        .HasColumnType("text");

                    b.Property<string>("imageUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("isMultipleChoice")
                        .HasColumnType("boolean");

                    b.Property<string>("majorId")
                        .HasColumnType("text");

                    b.Property<string>("subjectId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updatedBy")
                        .HasColumnType("text");

                    b.Property<string>("videoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("facultyId");

                    b.HasIndex("majorId");

                    b.HasIndex("subjectId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("Domain.Entites.ReplyComment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("commentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedBy")
                        .HasColumnType("text");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("likeCount")
                        .HasColumnType("integer");

                    b.Property<string>("receiverId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("commentId");

                    b.HasIndex("createdBy");

                    b.HasIndex("receiverId");

                    b.ToTable("ReplyComments");
                });

            modelBuilder.Entity("Domain.Entites.Student", b =>
                {
                    b.Property<string>("cardId")
                        .HasColumnType("text");

                    b.Property<string>("CourseId")
                        .HasColumnType("text");

                    b.Property<string>("classId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("facultyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("graduatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("joinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("majorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("cardId");

                    b.HasIndex("CourseId");

                    b.HasIndex("classId");

                    b.HasIndex("facultyId");

                    b.HasIndex("majorId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("Domain.Entites.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClassId")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedBy")
                        .HasColumnType("text");

                    b.Property<string>("facultyId")
                        .HasColumnType("text");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("majorId")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("thumbNail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("createdBy");

                    b.HasIndex("facultyId");

                    b.HasIndex("majorId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Domain.Entites.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("avatar")
                        .HasColumnType("text");

                    b.Property<DateTime?>("birth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("currentAddress")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedBy")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("fullName")
                        .HasColumnType("text");

                    b.Property<byte?>("gender")
                        .HasColumnType("smallint");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("nickname")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updatedBy")
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entites.Class", b =>
                {
                    b.HasOne("Domain.Entites.User", "User")
                        .WithMany("Classes")
                        .HasForeignKey("UserId");

                    b.HasOne("Domain.Entites.Faculty", "Faculty")
                        .WithMany("Classes")
                        .HasForeignKey("facultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Lecturer", "Lecturer")
                        .WithOne("Class")
                        .HasForeignKey("Domain.Entites.Class", "lecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Major", "Major")
                        .WithMany("Classes")
                        .HasForeignKey("majorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Lecturer");

                    b.Navigation("Major");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entites.Comment", b =>
                {
                    b.HasOne("Domain.Entites.User", "Sender")
                        .WithMany("Comments")
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Lesson", "Lesson")
                        .WithMany("Comments")
                        .HasForeignKey("lessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entites.Course", "Course")
                        .WithMany("Comments")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("Lesson");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.Entites.Course", b =>
                {
                    b.HasOne("Domain.Entites.User", "User")
                        .WithMany("Courses")
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Faculty", "Faculty")
                        .WithMany("Courses")
                        .HasForeignKey("facultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Major", "Major")
                        .WithMany("Courses")
                        .HasForeignKey("majorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Major");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entites.Exam", b =>
                {
                    b.HasOne("Domain.Entites.Class", null)
                        .WithMany("Exams")
                        .HasForeignKey("ClassId");

                    b.HasOne("Domain.Entites.User", null)
                        .WithMany("TesterExams")
                        .HasForeignKey("UserId");

                    b.HasOne("Domain.Entites.User", "CreatedUser")
                        .WithMany("CreatedUserExams")
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedUser");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Domain.Entites.ExamQuestion", b =>
                {
                    b.HasOne("Domain.Entites.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("examId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("questionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entites.ExamResultByUser", b =>
                {
                    b.HasOne("Domain.Entites.User", "User")
                        .WithMany("ExamResultsByUser")
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Exam", "Exam")
                        .WithMany("ExamResults")
                        .HasForeignKey("examId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entites.ExamSchedule", b =>
                {
                    b.HasOne("Domain.Entites.Class", "Class")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("classId");

                    b.HasOne("Domain.Entites.User", "createdUser")
                        .WithMany("CreatedExamSchedulesUser")
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Exam", "Exam")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("examId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Subject", "Subject")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.User", "superVisory")
                        .WithMany("ExamSuperVisor")
                        .HasForeignKey("superVisoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Exam");

                    b.Navigation("Subject");

                    b.Navigation("createdUser");

                    b.Navigation("superVisory");
                });

            modelBuilder.Entity("Domain.Entites.Faculty", b =>
                {
                    b.HasOne("Domain.Entites.User", "User")
                        .WithMany("Faculties")
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entites.Lecturer", b =>
                {
                    b.HasOne("Domain.Entites.Faculty", "Faculty")
                        .WithMany("Lecturers")
                        .HasForeignKey("facultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Major", "Major")
                        .WithMany("Lecturers")
                        .HasForeignKey("majorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.User", "User")
                        .WithOne("Lecturer")
                        .HasForeignKey("Domain.Entites.Lecturer", "userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Major");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entites.Lesson", b =>
                {
                    b.HasOne("Domain.Entites.Subject", null)
                        .WithMany("Lessons")
                        .HasForeignKey("SubjectId");

                    b.HasOne("Domain.Entites.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Domain.Entites.Major", b =>
                {
                    b.HasOne("Domain.Entites.User", "User")
                        .WithMany("Majors")
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Faculty", "Faculty")
                        .WithMany("Majors")
                        .HasForeignKey("facultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entites.Notify", b =>
                {
                    b.HasOne("Domain.Entites.Lecturer", null)
                        .WithMany("Notifies")
                        .HasForeignKey("LecturercardId");

                    b.HasOne("Domain.Entites.Student", null)
                        .WithMany("Notifies")
                        .HasForeignKey("StudentcardId");

                    b.HasOne("Domain.Entites.Class", "Class")
                        .WithMany("Notifies")
                        .HasForeignKey("classId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entites.User", "Sender")
                        .WithMany("CreatedNotifies")
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entites.Faculty", "Faculty")
                        .WithMany("Notifies")
                        .HasForeignKey("facultyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entites.Major", "Major")
                        .WithMany("Notifies")
                        .HasForeignKey("majorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entites.User", "Receiver")
                        .WithMany("ReceivedNotifies")
                        .HasForeignKey("receiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Class");

                    b.Navigation("Faculty");

                    b.Navigation("Major");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.Entites.Permisstion", b =>
                {
                    b.HasOne("Domain.Entites.User", "assignedUser")
                        .WithMany("AssignedPermisstionsUser")
                        .HasForeignKey("assignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.User", "createdUser")
                        .WithMany("CreatedPermisstionsUser")
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("assignedUser");

                    b.Navigation("createdUser");
                });

            modelBuilder.Entity("Domain.Entites.Question", b =>
                {
                    b.HasOne("Domain.Entites.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("facultyId");

                    b.HasOne("Domain.Entites.Major", "Major")
                        .WithMany()
                        .HasForeignKey("majorId");

                    b.HasOne("Domain.Entites.Subject", "Subject")
                        .WithMany("Questions")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Faculty");

                    b.Navigation("Major");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Domain.Entites.ReplyComment", b =>
                {
                    b.HasOne("Domain.Entites.Comment", "Comment")
                        .WithMany("ReplyComments")
                        .HasForeignKey("commentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.User", "Sender")
                        .WithMany("ReplyCommentsSender")
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.User", "Receiver")
                        .WithMany("ReplyCommentsReceiver")
                        .HasForeignKey("receiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.Entites.Student", b =>
                {
                    b.HasOne("Domain.Entites.Course", null)
                        .WithMany("Students")
                        .HasForeignKey("CourseId");

                    b.HasOne("Domain.Entites.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("classId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("facultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Major", "Major")
                        .WithMany("Students")
                        .HasForeignKey("majorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("Domain.Entites.Student", "userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Faculty");

                    b.Navigation("Major");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entites.Subject", b =>
                {
                    b.HasOne("Domain.Entites.Class", null)
                        .WithMany("Subjects")
                        .HasForeignKey("ClassId");

                    b.HasOne("Domain.Entites.User", "User")
                        .WithMany("CreatedSubjectsUser")
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Faculty", "Faculty")
                        .WithMany("Subjects")
                        .HasForeignKey("facultyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entites.Major", "Major")
                        .WithMany("Subjects")
                        .HasForeignKey("majorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Faculty");

                    b.Navigation("Major");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entites.Class", b =>
                {
                    b.Navigation("ExamSchedules");

                    b.Navigation("Exams");

                    b.Navigation("Notifies");

                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Domain.Entites.Comment", b =>
                {
                    b.Navigation("ReplyComments");
                });

            modelBuilder.Entity("Domain.Entites.Course", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Lessons");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entites.Exam", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("ExamResults");

                    b.Navigation("ExamSchedules");
                });

            modelBuilder.Entity("Domain.Entites.Faculty", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Courses");

                    b.Navigation("Lecturers");

                    b.Navigation("Majors");

                    b.Navigation("Notifies");

                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Domain.Entites.Lecturer", b =>
                {
                    b.Navigation("Class")
                        .IsRequired();

                    b.Navigation("Notifies");
                });

            modelBuilder.Entity("Domain.Entites.Lesson", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Domain.Entites.Major", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Courses");

                    b.Navigation("Lecturers");

                    b.Navigation("Notifies");

                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Domain.Entites.Question", b =>
                {
                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("Domain.Entites.Student", b =>
                {
                    b.Navigation("Notifies");
                });

            modelBuilder.Entity("Domain.Entites.Subject", b =>
                {
                    b.Navigation("ExamSchedules");

                    b.Navigation("Exams");

                    b.Navigation("Lessons");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Entites.User", b =>
                {
                    b.Navigation("AssignedPermisstionsUser");

                    b.Navigation("Classes");

                    b.Navigation("Comments");

                    b.Navigation("Courses");

                    b.Navigation("CreatedExamSchedulesUser");

                    b.Navigation("CreatedNotifies");

                    b.Navigation("CreatedPermisstionsUser");

                    b.Navigation("CreatedSubjectsUser");

                    b.Navigation("CreatedUserExams");

                    b.Navigation("ExamResultsByUser");

                    b.Navigation("ExamSuperVisor");

                    b.Navigation("Faculties");

                    b.Navigation("Lecturer")
                        .IsRequired();

                    b.Navigation("Majors");

                    b.Navigation("ReceivedNotifies");

                    b.Navigation("ReplyCommentsReceiver");

                    b.Navigation("ReplyCommentsSender");

                    b.Navigation("Student")
                        .IsRequired();

                    b.Navigation("TesterExams");
                });
#pragma warning restore 612, 618
        }
    }
}
